Controllers/ExerciseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using programmeringmed.NetProjekt.Data;
using programmeringmed.NetProjekt.Models;

namespace programmeringmed.NetProjekt.Controllers
{
    public class ExerciseController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ExerciseController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Exercise
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Exercise.Include(e => e.BodyPart);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Exercise/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var exerciseModel = await _context.Exercise
                .Include(e => e.BodyPart)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (exerciseModel == null)
            {
                return NotFound();
            }

            return View(exerciseModel);
        }

        // GET: Exercise/Create
        public IActionResult Create()
        {
            ViewData["BodyPartId"] = new SelectList(_context.BodyPart, "Id", "BodyPart");
            return View();
        }

        // POST: Exercise/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,ExerciseName,Description,VideoUrl,BodyPartId")] ExerciseModel exerciseModel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(exerciseModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["BodyPartId"] = new SelectList(_context.BodyPart, "Id", "BodyPart", exerciseModel.BodyPartId);
            return View(exerciseModel);
        }

        // GET: Exercise/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var exerciseModel = await _context.Exercise.FindAsync(id);
            if (exerciseModel == null)
            {
                return NotFound();
            }
            ViewData["BodyPartId"] = new SelectList(_context.BodyPart, "Id", "BodyPart", exerciseModel.BodyPartId);
            return View(exerciseModel);
        }

        // POST: Exercise/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ExerciseName,Description,VideoUrl,BodyPartId")] ExerciseModel exerciseModel)
        {
            if (id != exerciseModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(exerciseModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ExerciseModelExists(exerciseModel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["BodyPartId"] = new SelectList(_context.BodyPart, "Id", "BodyPart", exerciseModel.BodyPartId);
            return View(exerciseModel);
        }

        // GET: Exercise/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var exerciseModel = await _context.Exercise
                .Include(e => e.BodyPart)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (exerciseModel == null)
            {
                return NotFound();
            }

            return View(exerciseModel);
        }

        // POST: Exercise/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var exerciseModel = await _context.Exercise.FindAsync(id);
            if (exerciseModel != null)
            {
                _context.Exercise.Remove(exerciseModel);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ExerciseModelExists(int id)
        {
            return _context.Exercise.Any(e => e.Id == id);
        }

        public async Task<IActionResult> ExerciseShow(string search)
        {
            IQueryable<ExerciseModel> exercises = _context.Exercise;

            if (!string.IsNullOrEmpty(search))
            {
                string searchLower = search.ToLower(); // Convert search query to lower case

                exercises = exercises.Where(e =>
                    e.ExerciseName.ToLower().Contains(searchLower) || // Convert database value to lower case
                    e.BodyPart.BodyPart.ToLower().Contains(searchLower) // Convert database value to lower case
                );
            }

            // Now include the related entity (BodyPart)
            exercises = exercises.Include(e => e.BodyPart);

            return View(await exercises.ToListAsync());
        }


                
    }
}

Controllers/WorkoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using programmeringmed.NetProjekt.Data;
using programmeringmed.NetProjekt.Models;

namespace programmeringmed.NetProjekt.Controllers
{
    [Authorize]
    public class WorkoutController : Controller
    {
        private readonly ApplicationDbContext _context;

        public WorkoutController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Workout
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Workout.Include(w => w.BodyPart).Include(w => w.ExerciseForm);
            return View(await applicationDbContext.ToListAsync());
        }
        public async Task<IActionResult> Dashboard()
        {
            var username = User.Identity.Name;

            // Beräkna gränsvärdet för 30 dagar tillbaka i tiden
            var thirtyDaysAgo = DateTime.Today.AddDays(-30);

            // Hämta antal avslutade träningspass för varje typ av träning under de senaste 30 dagarna
            var gymCount = await _context.Workout
                .Where(w => w.Username == username && w.ExerciseFormId == 2 && w.Completed == true && w.Date >= thirtyDaysAgo && w.Date <= DateTime.Today)
                .CountAsync();

            var conditionCount = await _context.Workout
                .Where(w => w.Username == username && w.ExerciseFormId == 1 && w.Completed == true && w.Date >= thirtyDaysAgo && w.Date <= DateTime.Today)
                .CountAsync();

            var skiingCount = await _context.Workout
                .Where(w => w.Username == username && w.ExerciseFormId == 3 && w.Completed == true && w.Date >= thirtyDaysAgo && w.Date <= DateTime.Today)
                .CountAsync();

            // Räkna ihop totala antalet träningspass under de senaste 30 dagarna
            var totalWorkoutsCount = gymCount + conditionCount + skiingCount;

            // Hämta antalet träningspass per vecka för stapeldiagramet
            var weeklyWorkouts = new Dictionary<string, int>();

            // Beräkna antalet veckor sedan startdatumet
            int weeksCount = (int)Math.Ceiling((DateTime.Today - thirtyDaysAgo).TotalDays / 7);

            // Loopa över varje vecka
            for (int i = 0; i < weeksCount; i++)
            {
                var startDate = thirtyDaysAgo.AddDays(i * 7);
                var endDate = startDate.AddDays(6);

                var weeklyWorkoutsCount = await _context.Workout
                    .Where(w => w.Username == username && w.Completed == true && w.Date >= startDate && w.Date <= endDate)
                    .CountAsync();

                weeklyWorkouts.Add($"Week {i+1}", weeklyWorkoutsCount);
            }

            // Sätt data i ViewBag
            ViewBag.GymCount = gymCount;
            ViewBag.ConditionCount = conditionCount;
            ViewBag.SkiingCount = skiingCount;
            ViewBag.TotalWorkoutsCount = totalWorkoutsCount;
            ViewBag.WeeklyWorkouts = weeklyWorkouts;

            // Skicka datan till vyn
            return View();
        }


        // GET: Workout/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var workoutModel = await _context.Workout
                .Include(w => w.WorkoutExercises)
                    .ThenInclude(we => we.Exercise) // inkludera övningarna
                .Include(w => w.ExerciseForm) // inkludera exerciseform
                .Include(w => w.Condition) // inkludera kondition
                    .ThenInclude(c => c.ConditionForm) // inkludera condition form
                .Include(w => w.Condition) // inkludera kondition
                    .ThenInclude(c => c.ConditionType) // inkludera condition form
                .Include(w => w.BodyPart) // inkludera kroppsdel
                .Include(w => w.Skiing) // inkludera skidåkning
                    .ThenInclude(s => s.Method) // inkludera metod
                .Include(w => w.Skiing) // inkludera skidåkning
                    .ThenInclude(s => s.Focus) // inkludera fokus
                .Include(w => w.Skiing) // inkludera skidåkning
                    .ThenInclude(s => s.Discipline) // inkludera disciplin
                .Include(w => w.Skiing) // inkludera skidåkning
                    .ThenInclude(s => s.Organization) // inkludera organisation
                .FirstOrDefaultAsync(m => m.Id == id);

                    if (workoutModel == null)
                    {
                        return NotFound();
                    }

                    return View(workoutModel);
                }

        // GET: Workout/Create


        // GET: Workout/Create
        public IActionResult Create()
        {
            ViewData["BodyPartId"] = new SelectList(_context.BodyPart, "Id", "BodyPart");
            ViewData["ExerciseFormId"] = new SelectList(_context.ExerciseForm, "Id", "ExerciseForm");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Description,Date,BodyPartId,ExerciseFormId,Length,Rating,Comment")] WorkoutModel workoutModel)
        {
            if (ModelState.IsValid)
            {
                // Bestäm om träningspasset är slutfört baserat på datum
                workoutModel.Completed = DateTime.Today > workoutModel.Date;


                if (workoutModel.ExerciseFormId == 1) // Om "Kondition" är valt
                {
                    workoutModel.BodyPartId = null; // Sätt BodyPartId till null
                    workoutModel.SkiingId = null; // Sätt BodyPartId till null
                }
                else if (workoutModel.ExerciseFormId == 2)//Om gym är valt
                {
                    workoutModel.SkiingId = null; // Sätt BodyPartId till null
                }
                else if (workoutModel.ExerciseFormId == 3) // Om "Skiing" är valt
                {
                    workoutModel.Completed = true;
                    workoutModel.BodyPartId = null; // Sätt BodyPartId till null
                }

                // Hämta användarnamnet från identitetsautentiseringen
                workoutModel.Username = User.Identity?.Name;

                _context.Add(workoutModel);
                await _context.SaveChangesAsync();

                // Omdirigera beroende på vilken typ av träning som valdes
                if (workoutModel.ExerciseFormId == 1) // Om "Kondition" är valt
                {
                    return RedirectToAction("Create", "Condition", new { workoutId = workoutModel.Id }); // Redirect till index för Workout
                }
                else if (workoutModel.ExerciseFormId == 2) // Om "Gym" är valt
                {
                    // Redirect till WorkoutExercise/Create och inkludera id för det skapade träningspasset
                    return RedirectToAction("Create", "WorkoutExercise", new { workoutId = workoutModel.Id });
                }
                else if (workoutModel.ExerciseFormId == 3) // Om "Skiing" är valt
                {
                    // Redirect till SkiingModel/Create och inkludera id för det skapade träningspasset
                    return RedirectToAction("Create", "Skiing", new { workoutId = workoutModel.Id });
                }
            }
            ViewData["BodyPartId"] = new SelectList(_context.BodyPart, "Id", "BodyPart", workoutModel.BodyPartId);
            ViewData["ExerciseFormId"] = new SelectList(_context.ExerciseForm, "Id", "ExerciseForm", workoutModel.ExerciseFormId);
            return View(workoutModel);
        }

        // GET: Workout/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var workoutModel = await _context.Workout.FindAsync(id);
            if (workoutModel == null)
            {
                return NotFound();
            }
            ViewData["BodyPartId"] = new SelectList(_context.BodyPart, "Id", "BodyPart", workoutModel.BodyPartId);
            ViewData["ExerciseFormId"] = new SelectList(_context.ExerciseForm, "Id", "ExerciseForm", workoutModel.ExerciseFormId);
            return View(workoutModel);
        }

        // POST: Workout/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        // POST: Workout/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Description,Date,Completed,Comment,Rating,Length,Username,BodyPartId,ExerciseFormId,SkiingId, ConditionId")] WorkoutModel workoutModel)
        {
            if (id != workoutModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    // Hämta användarnamnet från autentiseringen
                    workoutModel.Username = User.Identity?.Name;

                    _context.Update(workoutModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!WorkoutModelExists(workoutModel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                if (workoutModel.ExerciseFormId == 1) // Condition
                {

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager


<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - programmeringmed.NetProjekt</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/programmeringmed.NetProjekt.styles.css" asp-append-version="true" />
</head>

<body>
    <div>
        <nav class="desktop">
            @if (SignInManager.IsSignedIn(User))
            {
                <a class="" asp-area="" asp-controller="Home" asp-action="IndexLoggedIn"> <img class="logo" src="/Images/logo2.svg" alt=""> </a>
            }
            else
            {
                <a class="" asp-area="" asp-controller="Home" asp-action="Index"> <img class="logo" src="/Images/logo2.svg" alt=""> </a>
            }

            @if (SignInManager.IsSignedIn(User))
            {

                <ul>

                    <li>
                        <img src="/Images/homev.png" alt="">
                        <a class="" asp-area="" asp-controller="Home" asp-action="IndexLoggedIn">Home</a>
                    </li>
                    <li>
                        <img src="/Images/activityv.png" alt="">
                        <a class="" asp-area="" asp-controller="Workout" asp-action="Index">Activity</a>
                    </li>
                    <li>
                        <img src="/Images/plusv.png" alt="">
                        <a class="" asp-area="" asp-controller="Workout" asp-action="Create">Add Data</a>
                    </li>
                    <li>
                        <img src="/Images/graphv.png" alt="">
                        <a class="" asp-area="" asp-controller="Workout" asp-action="Dashboard">Dashboard</a>
                    </li>
                    <li>
                        <img src="/Images/userv.png" alt="">
                        <a class="" asp-area="Identity" asp-page="/Account/Manage/Index" title="Manage">Profile</a>
                    </li>
                </ul>
            }
            else
            {
                <!-- Användaren är utloggad -->
                <ul>
                    <li>
                        <img src="/Images/runv.png" alt="">
                        <a class="" asp-controller="Exercise" asp-action="ExerciseShow">Exercises</a>
                    </li>
                    <li class="">
                        <img src="/Images/add-userv.png" alt="">
                        <a class="" asp-area="Identity" asp-page="/Account/Register">Register</a>
                    </li>
                    <li class="">
                        <img src="/Images/log-inv.png" alt="">
                        <a class="" asp-area="Identity" asp-page="/Account/Login">Login</a>
                    </li>
                </ul>
            }





        </nav>
        <header>
            <nav class="mobile">
                @if (SignInManager.IsSignedIn(User))
                {
                    <ul>
                        <li>
                            <img src="/Images/home.png" alt="">
                            <a class="" asp-area="" asp-controller="Home" asp-action="IndexLoggedIn">Home</a>
                        </li>
                        <li>
                            <img src="/Images/activity.png" alt="">
                            <a class="" asp-area="" asp-controller="Workout" asp-action="Index">Activity</a>
                        </li>
                        <li>
                            <img src="/Images/plus.png" alt="">
                            <a class="" asp-area="" asp-controller="Workout" asp-action="Create">Add Data</a>
                        </li>
                        <li>
                            <img src="/Images/graph.png" alt="">
                            <a class="" asp-area="" asp-controller="Workout" asp-action="Dashboard">Dashboard</a>
                        </li>
                        <li>
                            <img src="/Images/user.png" alt="">
                            <a class="" asp-area="Identity" asp-page="/Account/Manage/Index" title="Manage">Profile</a>
                        </li>
                    </ul>
                }
                else
                {
                    <ul>
                        <li>
                            <img src="/Images/run.png" alt="">
                            <a class="" asp-controller="Exercise" asp-action="ExerciseShow">Exercises</a>
                        </li>
                        <li class="">
                            <img src="/Images/add-user.png" alt="">
                            <a class="" asp-area="Identity" asp-page="/Account/Register">Register</a>
                        </li>
                        <li class="">
                            <img src="/Images/log-in.png" alt="">
                            <a class="" asp-area="Identity" asp-page="/Account/Login">Login</a>
                        </li>

                    </ul>
                }





            </nav>

        </header>
        <div class="container">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>
    </div>
    <footer class="mt-5">
        
        <p class="center">&copy; Copyright 2024 - Design Edwin Lundbäck</p>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>